#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : python-coveralls
Version  : 2.9.1
Release  : 1
URL      : https://files.pythonhosted.org/packages/2e/69/c702223d886b17a05fa356cca009e8e6dd8d7497e7268c9dbfab046b8cd6/python-coveralls-2.9.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/2e/69/c702223d886b17a05fa356cca009e8e6dd8d7497e7268c9dbfab046b8cd6/python-coveralls-2.9.1.tar.gz
Summary  : Python interface to coveralls.io API
Group    : Development/Tools
License  : Apache-2.0
Requires: python-coveralls-bin = %{version}-%{release}
Requires: python-coveralls-python = %{version}-%{release}
Requires: python-coveralls-python3 = %{version}-%{release}
Requires: PyYAML
Requires: coverage
Requires: requests
Requires: six
BuildRequires : buildreq-distutils3

%description
Python interface to coveralls.io API
        ====================================

%package bin
Summary: bin components for the python-coveralls package.
Group: Binaries

%description bin
bin components for the python-coveralls package.


%package python
Summary: python components for the python-coveralls package.
Group: Default
Requires: python-coveralls-python3 = %{version}-%{release}

%description python
python components for the python-coveralls package.


%package python3
Summary: python3 components for the python-coveralls package.
Group: Default
Requires: python3-core

%description python3
python3 components for the python-coveralls package.


%prep
%setup -q -n python-coveralls-2.9.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1542839383
python3 setup.py build

%install
rm -rf %{buildroot}
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/coveralls

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
